version: '3'

services:
  async-download-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/async/app
    command: python ./server.py --logging
